Algoritmo "aula23"
// Disciplina   : [Lógica de Programação]
// Professor   : QIKBYTE
// Descrição   : Aula 23 - Matriz
// Autor(a)    : Douglas
// Data atual  : 19/10/2021
Var
   matrizA: vetor[1..2,1..2] de inteiro
   i,j: inteiro


Inicio

   para i de 1 ate 2 faca
      para j de 1 ate 2 faca
         matrizA[i,j] <- 0
      fimpara
      para j de 1 ate 2 faca
         escreva (matrizA[i,j])
      fimpara
      escreval("")
   fimpara

Fimalgoritmo
