Algoritmo "aula14"
// Disciplina   : [Lógica de Programação]
// Professor   : QIKBYTE
// Descrição   : Aula 14 - Estrutura de repetição - PARA - Parte 2
// Autor(a)    : Douglas
// Data atual  : 06/10/2021
Var
   // Seção de declarações de variaveis
   i,valor: inteiro
Inicio

   escreva("Digite um valor para a tabuada: ")
   leia(valor)
   para i de 1 ate 10 faca

      escreval(valor , " X" , i , " = " , valor * i)
   fimpara



Fimalgoritmo
