Algoritmo "aula16"
// Disciplina   : [Lógica de Programação]
// Professor   : QIKBYTE
// Descrição   : Aula 16 - Estrutura de repetição - ENQUANTO - Parte 1
// Autor(a)    : Douglas
// Data atual  : 06/10/2021
Var
   // Seção de declarações de variaveis
   i: inteiro
Inicio

   enquanto i <= 20 faca
      i <- i +1
      se i mod 2 = 0 entao
         escreva(i)
      fimse
   fimenquanto

Fimalgoritmo
